[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "lib-ml-remla25-team12"
dynamic = ["version"]
dependencies = [
    "nltk",
    "scikit-learn"
]

[tool.setuptools_scm]