[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "libml"
dynamic = ["version"]
dependencies = [
    "nltk",
    "scikit-learn"
]

[tool.setuptools_scm]
write_to = "libml/_version.py"
